Repository shardeum/archiver, pull requests merged in 2024-09, with the labels that each got.

#72 BLUE-255 hot-fix: ApplyTimestamp calculation logic fix
  src/Data/Collector.ts
Labels: Review effort [1-5]: 2

#79 fix: Updated beforeStateAccounts → beforeStates as per the new receipt structure
  src/Data/Collector.ts
Labels: Review effort [1-5]: 2

#74 BLUE-257: Sending auth data for socket based subscription with validator
  src/Data/Data.ts
Labels: Review effort [1-5]: 2

#65 RED-201 Network Generated Transactions
  src/API.ts
  src/Data/Cycles.ts
  src/ServiceQueue.ts
  src/sync-v2/index.ts
  src/sync-v2/queries.ts
  src/sync-v2/verify.ts
Labels: Review effort [1-5]: 4

#83 RED-258: shutdown handler refactor
  src/ServiceQueue.ts
Labels: Review effort [1-5]: 2

#84 BLUE-273 Worker processed debug log flag
  src/Config.ts
  src/primary-process/index.ts
Labels: Review effort [1-5]: 3
