Repository shardeum/archiver, pull requests merged in 2025-05, with the labels that each got.

#242 SHARD-2420 : Fixes archiver issue where successful receipts get overwritten by newer failure receipts
  src/Config.ts
  src/Data/Collector.ts
  src/Data/DataLogWriter.ts
Labels: Review effort 4/5

#246 include hotfix in ci
  .github/workflows/ci.yml
Labels: Review effort 1/5

#247 Update ci.yml
  .github/workflows/ci.yml
Labels: Review effort 1/5

#257 added sec.md
  SECURITY.md
Labels: Review effort 1/5

#256 SHARD-2447: remove restriction for activeArchiver length smaller than 4
  src/Data/Data.ts
Labels: Review effort 2/5

#260 SHARD-2464 - Update keys
  static/devnet.genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 1/5

#255 SHARD-2445: Prevent checkpointing from overwriting successful receipt with majority-fail
  src/checkpoint/CheckpointData.ts
  test/unit/src/checkpoint/CheckpointData.test.ts
Labels: Review effort 3/5

#219 SHARD-2394 - txDigestFunctions unit tests
  test/unit/src/txDigester/txDigestFunctions.test.ts
Labels: Review effort 3/5

#218 SHARD-2393 - txDigester index.ts unit tests
  test/unit/src/txDigester/index.test.ts
Labels: Review effort 2/5

#221 Add unit tests archivedCycle/Gossip.ts
  test/unit/src/archivedCycle/Gossip.test.ts
Labels: Review effort 3/5

#250 SHARD-2398 - add unit tests for allowedArchiversManager.ts
  test/unit/src/shardeum/allowedArchiversManager.test.ts
Labels: Review effort 3/5

#214 SHARD-2402 - add unit tests for archiver_data_sync_check.ts
  scripts/archiver_data_sync_check.ts
  test/unit/scripts/archiver_data_sync_check.test.ts
Labels: Review effort 3/5

#263 SHARD-2450: Fix OOM issue in checkpoint v2
  .gitignore
  src/checkpoint/CheckpointV2.ts
  src/dbstore/checkpointStatus.ts
  src/server.ts
  src/utils/cycleTracker.ts
  test/unit/src/utils/cycleTracker.test.ts
Labels: Review effort 4/5
