Repository shardeum/archiver, pull requests merged in 2025-04, with the labels that each got.

#196 SHARD-2159: allow files specified in env vars to set genesis secure accounts
  src/services/transactionVerification.ts
Labels: Review effort 2/5

#201 SHARD-2180 - Update data
  static/devnet.genesis-secure-accounts.json
  static/genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 2/5

#204 SHARD-2186: Implement batch processing for account insertions
  scripts/archiver_config_sign.ts
  src/Config.ts
  src/dbstore/accounts.ts
  src/services/transactionVerification.ts
  test/unit/src/Config.test.ts
  test/unit/src/Crypto.test.ts
  test/unit/src/Logger.test.ts
  test/unit/src/P2P.test.ts
  test/unit/src/dbstore/accounts.test.ts
  test/unit/src/dbstore/cycles.test.ts
  test/unit/src/dbstore/receipts.test.ts
  test/unit/src/dbstore/sqlite3storage.test.ts
  test/unit/src/saveConsoleOutput.test.ts
  test/unit/src/utils/serialization/SchemaHelpers.test.ts
Labels: Review effort 3/5

#209 SHARD-2189 4725-data-import
  static/devnet.genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 1/5

#208 SHARD-2186: Fix index advancement and batch size calculation
  src/dbstore/accounts.ts
Labels: Review effort 3/5

#213 SHARD-2189 - Data import #2.
  static/genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
Labels: Review effort 2/5

#215 SHARD-2189 - Data import #2. - cherrypick
  static/genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
Labels: Review effort 2/5

#203 SHARD-2185: Update checkpoint radix sharing to create missing buckets
  src/API.ts
  src/checkpoint/CheckpointData.ts
Labels: Review effort 3/5

#205 SHARD-2185 : handles invalid receipts in data processing
  src/Data/Collector.ts
Labels: Review effort 2/5

#216 SHARD-2203 4825-data-1
  static/devnet.genesis-secure-accounts.json
  static/genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 2/5

#212 SHARD-2185: Update checkpoint radix sharing to create missing buckets
  src/API.ts
  src/checkpoint/CheckpointData.ts
Labels: Review effort 3/5

#222 SHARD_2227 - Data export
  static/devnet.genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 1/5

#223 SHARD-2232 - Data export
  static/genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
Labels: Review effort 1/5

#228 SHARD-2241 - Update accounts
  static/genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
Labels: Review effort 2/5

#230 replace JSON.stringify with safeStringify
  scripts/update_network_account_listOfChanges.ts
  src/API.ts
  src/Data/Data.ts
  src/State.ts
  src/services/transactionVerification.ts
  src/sync-v2/index.ts
Labels: Review effort 3/5

#195 SHARD-2155 - refactor: update error responses in API to return structured JSON format
  src/API.ts
Labels: Review effort 2/5

#231 SHARD-2242 - Fix: empty previous cycle marker
  src/Data/Data.ts
  src/cache/cycleRecordsCache.ts
Labels: Review effort 2/5

#234 SHARD-2253
  static/devnet.genesis-secure-accounts.json
  static/genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/mainnet.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 2/5

#233 SHARD-2216 : everything from shard 2234, shard 2235 and shard 2236 in 1 pr
  src/Data/Collector.ts
  src/dbstore/receipts.ts
  src/shardeum/calculateAccountHash.ts
  src/shardeum/verifyGlobalTxReceipt.ts
  test/unit/src/calculateAccountHash.test.ts
  test/unit/src/shardeum/verifyGlobalTxReceipt.test.ts
Labels: Review effort 4/5

#239 SHARD-2299 - Update Json
  static/devnet.genesis-secure-accounts.json
  static/local.genesis-secure-accounts.json
  static/stagenet.genesis-secure-accounts.json
  static/testnet.genesis-secure-accounts.json
Labels: Review effort 1/5
